- name: set expansion not required status
  include_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_k8s_status_conditions:
      - type: "{{ condition_expand_keyname }}Expansion"
        status: "False"
        reason: "NotRequired"
        message: "Storage/PVC '{{ condition_expand_keyname }}' does not require expansion"
