- name: php-fpm resource definitions
  vars:
    name: php-fpm
    k8s_state: "{{ php_fpm_state }}"
    component: php-fpm
    metadata_app: "{{ php_fpm_appname }}"
  block:
    - import_tasks: resource/cm.yml

    - import_tasks: resource/deploy.yml

    - import_tasks: resource/hpa.yml
      when: php_fpm_hpa_spec is defined and php_fpm_hpa_spec

    - import_tasks: resource/vpa.yml
      when: php_fpm_vpa_spec is defined and php_fpm_vpa_spec

    - import_tasks: resource/service.yml
