- name: import tasks
  block:
    - name: handle php-fpm
      import_tasks: "{{ role_path }}/tasks/php-fpm.yml"

    - name: set suspended condition
      import_tasks: "{{ common_path }}/condition/suspended/suspended.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
