- name: set successful status
  import_tasks: "{{ common_path }}/k8s/status.yml"
  vars:
    notify_status_force: true
    k8s_status_properties:
      ready: "True"
      created: "True"
      state: Ready
    k8s_status_conditions:
      - type: "Ready"
        status: "True"
        reason: "Successful"
        message: "All tasks completed successfully"
      - type: "Created"
        status: "True"
        reason: "Created"
        message: "The site has been created"
