- name: set successful status
  import_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_status_cr_notify_force: true
    routine_k8s_status_properties:
      ready: "True"
      created: "True"
      state: Ready
    routine_k8s_status_conditions:
      - type: "Ready"
        status: "True"
        reason: "Successful"
        message: "All tasks completed successfully"
      - type: "Created"
        status: "True"
        reason: "Created"
        message: "The site has been created"
