- name: pgbouncer readonly vpa resource definition
  vars:
    k8s_kind: VerticalPodAutoscaler
    k8s_state: "{{ pgbouncer_readonly_vpa_state | default(pgbouncer_state) }}"
    template: "{{ vpa_template }}"
    metadata_name: "{{ pgbouncer_readonly_vpa }}"
    annotations: "{{ pgbouncer_readonly_vpa_annotations | default(false) }}"
    vpa_ref_api_version: apps/v1
    vpa_ref_kind: Deployment
    vpa_ref_name: "{{ pgbouncer_readonly_deploy }}"
    vpa_spec: "{{ pgbouncer_readonly_vpa_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save pgbouncer readonly vpa resource definition task
  set_fact:
    k8s_pgbouncer_readonly_vpa: "{{ k8s_object_task }}"
