- name: nfs resource definitions
  vars:
    name: nfs
    k8s_state: "{{ server_state }}"
    component: nfs
    metadata_app: "{{ server_appname }}"
    # pvc autoexpansion
    pvc_info_autoexpansion: "{{ server_pvc_autoexpansion }}"
    pvc_info_keyname: server
    pvc_info_container_group: "{{ server_container_group }}"
    pvc_info_name: "{{ server_pvc }}"
    pvc_info_increment_gib: "{{ server_pvc_autoexpansion_gib }}"
    pvc_info_cap_gib: "{{ server_pvc_autoexpansion_cap_gib  }}"
    condition_expand_keyname: "{{ pvc_info_keyname | capitalize }}"
  block:
    - import_tasks: nfs/resources/pvc.yml

    - import_tasks: "{{ common_path }}/pvc-info.yml"

    - import_tasks: nfs/resources/server.yml

    - import_tasks: nfs/resources/sc.yml
