apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/krestomatio/m4e-operator
        - https://github.com/krestomatio/nfs-operator
      changes:
        - regex:
            pattern: "COLLECTION_BRANCH \\?= (.*)"
            files:
              - "Makefile"
