apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/krestomatio/keydb-operator
      changes:
        - regex:
            pattern: "COLLECTION_VERSION \\?= (.*)"
            files:
              - "Makefile"
