- name: postgres resource definitions
  vars:
    name: postgres
    k8s_state: "{{ postgres_state }}"
    component: postgres
    metadata_app: "{{ postgres_appname }}"
  block:
    - import_tasks: resource/secret.yml

    - import_tasks: resource/deploy.yml

    - import_tasks: resource/service.yml

    - import_tasks: resource/pvc.yml
