- name: pgbouncer readonly resource definitions
  vars:
    name: pgbouncer
    component: pgbouncer
    metadata_app: "{{ pgbouncer_readonly_appname }}"
  block:
    - import_tasks: resource/pgbouncer-readonly/secret.yml

    - import_tasks: resource/pgbouncer-readonly/cm.yml

    - import_tasks: resource/pgbouncer-readonly/svc.yml

    - import_tasks: resource/pgbouncer-readonly/deploy.yml

    - import_tasks: resource/pgbouncer-readonly/vpa.yml
      when: pgbouncer_readonly_vpa_spec is defined and pgbouncer_readonly_vpa_spec
