- name: pgbouncer resource definitions
  vars:
    name: pgbouncer
    component: pgbouncer
    metadata_app: "{{ pgbouncer_appname }}"
    runtime: pgbouncer
  block:
    - import_tasks: resource/pgbouncer/netpol.yml
      when: not pgbouncer_netpol_omit

    - import_tasks: resource/pgbouncer/secret.yml

    - import_tasks: resource/pgbouncer/cm.yml

    - import_tasks: resource/pgbouncer/svc.yml

    - import_tasks: resource/pgbouncer/deploy.yml

    - import_tasks: resource/pgbouncer/vpa.yml
      when: pgbouncer_vpa_spec is defined and pgbouncer_vpa_spec
