- name: postgres resource definitions
  vars:
    name: postgres
    component: postgres
    metadata_app: "{{ postgres_appname }}"
    runtime: postgres
  block:
    - import_tasks: resource/postgres/netpol.yml
      when: not postgres_netpol_omit

    - import_tasks: resource/postgres/secret.yml

    - import_tasks: resource/postgres/cm.yml

    - import_tasks: resource/postgres/cm-vars.yml

    - import_tasks: resource/postgres/svc.yml

    - import_tasks: resource/postgres/sts.yml

    - import_tasks: resource/postgres/vpa.yml
      when: postgres_vpa_spec is defined and postgres_vpa_spec
