- name: postgres readreplicas resource definitions
  vars:
    name: readreplicas
    component: readreplicas
    metadata_app: "{{ postgres_readreplicas_appname }}"
  block:
    - import_tasks: resource/readreplicas/svc.yml

    - import_tasks: resource/readreplicas/svc-readonly.yml

    - import_tasks: resource/readreplicas/sts.yml

    - import_tasks: "{{ common_path }}/cleanup-resources.yml"
      vars:
        cleanup_label_selector: "app={{ metadata_app }}"
        cleanup_kind_list:
          - PersistentVolumeClaim
