- name: keydb resource definitions
  vars:
    name: keydb
    k8s_state: "{{ keydb_state }}"
    component: keydb
    metadata_app: "{{ keydb_appname }}"
  block:
    # remove sts
    - import_tasks: resource/sts.yml

    - import_tasks: "{{ common_path }}/cleanup-resources.yml"
      vars:
        cleanup_label_selector: "app={{ metadata_app }}"
        cleanup_kind_list:
          - PersistentVolumeClaim
