- name: keydb resource definitions
  vars:
    name: keydb
    k8s_state: "{{ keydb_state }}"
    component: keydb
    metadata_app: "{{ keydb_appname }}"
  block:
    - include_tasks: "resource/{{ keydb_ingress_type }}.yml"
      when: keydb_ingress_deploy | bool

    - import_tasks: resource/sts.yml

    - import_tasks: resource/svc.yml

    - import_tasks: resource/svc-headless.yml

    - import_tasks: resource/cm.yml

    - import_tasks: resource/secret.yml
