- name: nginx config map resource definition
  vars:
    k8s_kind: ConfigMap
    k8s_state: "{{ nginx_cm_state | default(nginx_state) }}"
    template: "{{ cm_template }}"
    metadata_name: "{{ nginx_cm }}"
    cm_data: "{{ nginx_cm_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save nginx config map resource definition task
  set_fact:
    k8s_nginx_cm: "{{ k8s_object_task }}"
