- name: nginx hpa resource definition
  vars:
    k8s_kind: HorizontalPodAutoscaler
    k8s_state: "{{ nginx_hpa_state | default(nginx_state) }}"
    template: "{{ hpa_template }}"
    metadata_name: "{{ nginx_hpa }}"
    annotations: "{{ nginx_hpa_annotations | default(false) }}"
    hpa_ref_api_version: apps/v1
    hpa_ref_kind: Deployment
    hpa_ref_name: "{{ nginx_deploy }}"
    hpa_spec: "{{ nginx_hpa_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save nginx hpa resource definition task
  set_fact:
    k8s_nginx_hpa: "{{ k8s_object_task }}"
