- name: nginx ingress resource definition
  vars:
    k8s_kind: Ingress
    k8s_state: "{{ nginx_ingress_state | default(nginx_state) }}"
    template: "{{ ingress_template }}"
    metadata_name: "{{ nginx_ingress }}"
    annotations: "{{ nginx_ingress_annotations | default(false) }}"
    ingress_spec: "{{ nginx_ingress_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save nginx ingress resource definition task
  set_fact:
    k8s_nginx_ingress: "{{ k8s_object_task }}"
