- name: nginx ingress resource definition
  vars:
    k8s_kind: Ingress
    k8s_state: "{{ nginx_ingress_state | default(nginx_state) }}"
    template: "{{ ingress_template }}"
    metadata_name: "{{ nginx_ingress }}"
    annotations: "{{ nginx_ingress_annotations | default(false) }}"
    ingress_spec: "{{ nginx_ingress_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save nginx ingress resource definition task
  set_fact:
    k8s_nginx_ingress: "{{ k8s_object_task }}"

- name: wait for nginx ingress
  when:
    - _nginx_ingress_wait_for_ip | default(false)
    - k8s_nginx_ingress is changed
    - "'absent' not in nginx_ingress_state | default(nginx_state)"
  include_tasks: "{{ common_path }}/ingress-wait.yml"
