- name: nginx network policy resource definition
  vars:
    k8s_kind: NetworkPolicy
    k8s_state: "{{ nginx_netpol_state | default(nginx_state) }}"
    template: "{{ netpol_template }}"
    metadata_name: "{{ nginx_netpol }}"
    netpol_spec: "{{ nginx_netpol_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save nginx netpol resource definition task
  set_fact:
    k8s_nginx_netpol: "{{ k8s_object_task }}"
