- name: set status
  when:
    # https://github.com/operator-framework/operator-sdk-ansible-util/issues/18
    - not ansible_check_mode
    - not k8s_status_omit | default(false)
  register: k8s_status_task
  k8s_status:
    api_version: "{{ k8s_status_api_version | default(cr_api_version) }}"
    kind: "{{ k8s_status_kind | default(cr_kind) }}"
    name: "{{ k8s_status_name | default(meta_name) }}"
    namespace: "{{ k8s_status_namespace | default(meta_namespace) }}"
    status: "{{ k8s_status_properties | default(omit,true) }}"
    conditions: "{{ k8s_status_conditions | default(omit,true) }}"
    replace_lists: "{{ k8s_status_replace_lists | default(omit,true) }}"


- name: notify status
  when: notify_status is defined and notify_status
  import_tasks: "{{ common_path }}/k8s/status-notify.yml"
