- name: set database not instantiated status
  include_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    last_transition_time: "{{ now(utc=True).isoformat(timespec='seconds') + 'Z' }}"
    routine_k8s_status_properties:
      ready: "False"
      state: "DatabaseNotInstantiated"
      instantiated: "False"
    routine_k8s_status_conditions:
      - type: "Instantiated"
        status: "False"
        reason: "DatabaseNotInstantiated"
        message: "Database is about to be instantiated"
        lastTransitionTime: "{{ last_transition_time }}"
      - type: "Created"
        status: "False"
        reason: "DatabaseNotInstantiated"
        message: "Database is about to be instantiated"
        lastTransitionTime: "{{ last_transition_time }}"
      - type: "Ready"
        status: "False"
        reason: "DatabaseNotInstantiated"
        message: "Database is about to be instantiated"
        lastTransitionTime: "{{ last_transition_time }}"
