- name: import tasks
  block:
    - name: make assertions
      import_tasks: "{{ role_path }}/tasks/assertions.yml"

    - name: handle php-fpm
      import_tasks: "{{ role_path }}/tasks/php-fpm.yml"

    - name: include successful status
      import_tasks: "{{ common_path }}/condition/ready/successful.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
