- name: set state absent
  set_fact:
    state: absent
    k8s_wait: "{{ cr_state_wait | default(false) | bool }}"

- name: import tasks
  block:
    - name: start terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/start.yml"

    - name: handle nginx removal
      import_tasks: nginx.yml

    - name: handle moodle removal
      import_tasks: moodle.yml

    - name: end terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/end.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
