- name: moodle resource definitions
  vars:
    name: moodle
    k8s_state: "{{ moodle_state }}"
    component: "{{ moodle_component | default('moodle') }}"
    metadata_app: "{{ moodle_metadata_app | default(moodle_appname) }}"
  block:
    - import_tasks: resource/service.yml

    - import_tasks: resource/cronjob.yml

    - import_tasks: cleanup-jobs.yml

    - import_tasks: resource/deploy.yml

    - import_tasks: resource/secret-admin.yml

    - import_tasks: resource/secret-config.yml

    - import_tasks: resource/pvc-moodledata.yml
