- name: moodle resource definitions
  vars:
    name: moodle
    k8s_state: "{{ moodle_state }}"
    component: "{{ moodle_component | default('moodle') }}"
    metadata_app: "{{ moodle_metadata_app | default(moodle_appname) }}"
  block:
    - import_tasks: moodle/resource/service.yml

    - import_tasks: moodle/resource/job-new-instance.yml

    - import_tasks: moodle/resource/cronjob.yml

    - import_tasks: moodle/cleanup-jobs.yml

    - import_tasks: moodle/resource/deploy.yml

    - import_tasks: moodle/resource/secret-admin.yml

    - import_tasks: moodle/resource/secret-config.yml

    - import_tasks: moodle/resource/pvc-moodledata.yml
