---
# defaults file for postgres
cr_group: postgres.krestomat.io
cr_kind: Postgres

# custom resource state: present, absent, suspended
cr_state: present

meta_name_max_length: 20

# templates
postgres_sts_spec_template: sts/postgres-spec.yaml.j2
postgres_readreplicas_sts_spec_template: sts/readreplicas-spec.yaml.j2
pgbouncer_deploy_spec_template: deploy/pgbouncer-spec.yaml.j2
pgbouncer_readonly_deploy_spec_template: deploy/pgbouncer-readonly-spec.yaml.j2

# common labels
meta_app_created_by: postgres-operator
