- name: keydb ingress resource definition
  vars:
    k8s_kind: Ingress
    k8s_state: "{{ keydb_ingress_state | default(keydb_state) }}"
    template: "{{ ingress_template }}"
    metadata_name: "{{ keydb_ingress }}"
    annotations: "{{ keydb_ingress_annotations | default(false) }}"
    ingress_spec: "{{ keydb_ingress_spec }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save keydb ingress resource definition task
  set_fact:
    k8s_keydb_ingress: "{{ k8s_object_task }}"

- name: wait for keydb ingress
  when:
    - _keydb_ingress_wait_for_ip | default(keydb_ingress_wait_for_ip) | default(false)
    - k8s_keydb_ingress is changed
    - "'absent' not in keydb_ingress_state | default(keydb_state)"
  include_tasks: "{{ common_path }}/ingress-wait.yml"
