- name: keydb network policy resource definition
  vars:
    k8s_kind: NetworkPolicy
    k8s_state: "{{ keydb_netpol_state | default(keydb_state) }}"
    template: "{{ netpol_template }}"
    metadata_name: "{{ keydb_netpol }}"
    netpol_spec: "{{ keydb_netpol_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save keydb netpol resource definition task
  set_fact:
    k8s_keydb_netpol: "{{ k8s_object_task }}"
