- name: keydb secret resource definition
  vars:
    k8s_kind: Secret
    k8s_state: "{{ keydb_secret_state | default(keydb_state) }}"
    template: "{{ secret_template }}"
    metadata_name: "{{ keydb_secret }}"
    secret_data: "{{ keydb_secret_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save keydb secret resource definition task
  set_fact:
    k8s_keydb_secret: "{{ k8s_object_task }}"
