- name: import tasks
  block:
    - name: handle postgres
      import_tasks: postgres.yml

    - name: handle graphql-engine
      import_tasks: graphql-engine.yml

    - name: include successful status
      import_tasks: "{{ common_path }}/condition/ready/successful.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
