- name: (nfs) ganesha server network policy resource definition
  vars:
    k8s_kind: NetworkPolicy
    k8s_state: "{{ ganesha_netpol_state | default(ganesha_state) }}"
    template: "{{ netpol_template }}"
    metadata_name: "{{ ganesha_netpol }}"
    netpol_spec: "{{ ganesha_netpol_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save (nfs) ganesha server netpol resource definition task
  set_fact:
    k8s_ganesha_netpol: "{{ k8s_object_task }}"
