- name: ganesha vpa resource definition
  vars:
    k8s_kind: VerticalPodAutoscaler
    k8s_state: "{{ ganesha_vpa_state | default(ganesha_state) }}"
    template: "{{ vpa_template }}"
    metadata_name: "{{ ganesha_vpa }}"
    annotations: "{{ ganesha_vpa_annotations | default(false) }}"
    vpa_ref_api_version: apps/v1
    vpa_ref_kind: StatefulSet
    vpa_ref_name: "{{ ganesha_sts }}"
    vpa_spec: "{{ ganesha_vpa_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save ganesha vpa resource definition task
  set_fact:
    k8s_ganesha_vpa: "{{ k8s_object_task }}"
