- name: server deploy
  vars:
    metadata_name: "{{ server_deploy }}"
    runtime: server
    annotations: "{{ server_deploy_annotations | default(false) }}"
    extra_labels: "{{ server_deploy_extra_labels | default(false) }}"
    connects_to: "{{ server_connects_to }}"
    inventory_include: true
  block:
    - name: set server deploy spec
      when: server_deploy_spec is not defined
      set_fact:
        server_deploy_spec: "{{ lookup('template', server_deploy_spec_template) }}"

    - name: server deploy resource definition
      vars:
        k8s_kind: Deployment
        k8s_state: "{{ server_deploy_state | default(server_state) }}"
        k8s_wait: "{{ server_deploy_wait | default(true) }}"
        k8s_wait_timeout: "{{ server_deploy_wait_timeout | default(120) }}"
        template: "{{ deploy_template }}"
        deploy_spec: "{{ server_deploy_spec }}"
      import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save server deploy resource definition task output
  set_fact:
    k8s_server_deploy: "{{ k8s_object_task }}"
