- name: server route resource definition
  vars:
    k8s_kind: Route
    k8s_state: "{{ server_route_state | default(server_state) }}"
    template: "{{ route_template }}"
    metadata_name: "{{ server_route }}"
    annotations: "{{ server_route_annotations | default(false) }}"
    route_spec: "{{ server_route_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save server route resource definition task
  set_fact:
    k8s_server_route: "{{ k8s_object_task }}"
