- name: set update complete status
  include_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_k8s_status_properties:
      ready: "False"
      state: UpdateComplete
    routine_k8s_status_conditions:
      - type: "UpToDate"
        status: "False"
        reason: "{{ moodle_status_version.pendingType | default('Other') }}UpdateComplete"
        message: "{{ moodle_status_version.pendingType | default('Other') }} update of Moodle is complete"
      - type: "Ready"
        status: "False"
        reason: "UpdateComplete"
        message: "A Moodle update is complete"
