- name: set older code status
  include_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    this_routine_k8s_status_properties:
      ready: "False"
      state: "Downgraded"
      upToDate: "False"
    _routine_k8s_status_properties:
      "{{ routine_k8s_status_properties |  default({}) | combine(this_routine_k8s_status_properties) }}"
    routine_k8s_status_conditions:
      - type: "UpToDate"
        status: "False"
        reason: "Downgraded"
        message: "Moodle code is older than the version in the database"
      - type: "Ready"
        status: "False"
        reason: "Downgraded"
        message: "Moodle code is older than the version in the database"
