- name: set update pending status
  include_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_k8s_status_conditions:
      - type: "UpToDate"
        status: "False"
        reason: "{{ moodle_status_version.type | default('Other') }}UpdatePending"
        message: "{{ moodle_status_version.type | default('Other') }} update of Moodle is pending"
      - type: "Ready"
        status: "False"
        reason: "UpdatePending"
        message: "A Moodle update is pending"
