- name: set update pending status
  include_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    this_routine_k8s_status_properties:
      ready: "False"
      state: "UpdatePending"
      upToDate: "False"
    _routine_k8s_status_properties:
      "{{ routine_k8s_status_properties |  default({}) | combine(this_routine_k8s_status_properties) }}"
    routine_k8s_status_conditions:
      - type: "UpToDate"
        status: "False"
        reason: "{{ moodle_status_version.pendingType | default('Other') }}UpdatePending"
        message: "{{ moodle_status_version.pendingType | default('Other') }} update of Moodle is pending"
      - type: "Ready"
        status: "False"
        reason: "UpdatePending"
        message: "A Moodle update is pending"
