# moodle php-fpm
moodle_php_fpm: "{{ moodle_appname }}-php-fpm"
moodle_php_fpm_spec: |-
  {% for _php_fpm_varname in query('varnames', '^php_fpm.+')  %}
  {% set _php_fpm_vartype = lookup('vars', _php_fpm_varname) | type_debug %}
  {% if _php_fpm_vartype == 'bool' %}
  {{ _php_fpm_varname }}: {{ lookup('vars', _php_fpm_varname) }}
  {% elif _php_fpm_vartype == 'list' or _php_fpm_vartype == 'dict'  %}
  {{ _php_fpm_varname }}:
    {{ lookup('vars', _php_fpm_varname) | to_nice_yaml(indent=2) | indent(2) -}}
  {% else %}
  {{ _php_fpm_varname }}: "{{ lookup('vars', _php_fpm_varname) }}"
  {% endif %}
  {% endfor %}

# moodle nginx
moodle_nginx: "{{ moodle_appname }}-nginx"
moodle_nginx_spec: |-
  {% for _nginx_varname in query('varnames', '^php_fpm.+')  %}
  {% set _nginx_vartype = lookup('vars', _nginx_varname) | type_debug %}
  {% if _nginx_vartype == 'bool' %}
  {{ _nginx_varname }}: {{ lookup('vars', _nginx_varname) }}
  {% elif _nginx_vartype == 'list' or _nginx_vartype == 'dict'  %}
  {{ _nginx_varname }}:
    {{ lookup('vars', _nginx_varname) | to_nice_yaml(indent=2) | indent(2) -}}
  {% else %}
  {{ _nginx_varname }}: "{{ lookup('vars', _nginx_varname) }}"
  {% endif %}
  {% endfor %}

# moodle routine
moodle_routine: "{{ moodle_appname }}-routine"
moodle_routine_spec: |
  k8s_status_api_version: '{{ cr_api_version }}'
  k8s_status_kind: '{{ cr_kind }}'
  k8s_status_name: '{{ meta_name }}'
  k8s_status_namespace: '{{ meta_namespace }}'
  {% if notify_status is defined and notify_status %}
  notify_status:
    {{ notify_status | to_nice_yaml | indent(2) }}
  {% endif %}
  pods_ready_group: '{{ pods_ready_group }}'
  moodle_container_group: '{{ moodle_container_group }}'
  moodle_secret_config: '{{ moodle_secret_config }}'
  moodle_config_autosync: {{ moodle_config_autosync }}
  moodle_app: '{{ moodle_app }}'
  moodle_status_script: '{{ moodle_status_script }}'
  moodle_status_usage: {{ moodle_status_usage }}
  {% if moodle_status_checks is defined and moodle_status_checks %}
  moodle_status_checks: '{{ moodle_status_checks }}'
  {% endif %}
  moodle_status_version: false
  {% if moodle_redis_muc_store | bool and moodle_redis_muc_store_routine | bool %}
  moodle_redis_host: '{{ moodle_redis_host }}'
  moodle_redis_secret_auth_secret: '{{ moodle_redis_secret_auth_secret }}'
  moodle_redis_secret_auth_key: '{{ moodle_redis_secret_auth_key }}'
  {%    if moodle_redis_secret_auth_secret | string == 'False' %}
  moodle_redis_password: '{{ moodle_redis_password }}'
  {%    endif %}
  {%    if moodle_redis_muc_store_routine_script != moodle_redis_muc_store_script %}
  moodle_redis_muc_store_routine_script: '{{ moodle_redis_muc_store_routine_script }}'
  {%    else %}
  moodle_redis_muc_store: {{ moodle_redis_muc_store }}
  moodle_redis_muc_store_routine: {{ moodle_redis_muc_store_routine }}
  moodle_redis_muc_store_overwrite: true
  moodle_redis_muc_store_reset: {{ moodle_redis_muc_store_reset }}
  moodle_redis_muc_store_plugin: '{{ moodle_redis_muc_store_plugin }}'
  moodle_redis_muc_store_name: '{{ moodle_redis_muc_store_name }}'
  moodle_redis_muc_store_script_extra_config: '{{ moodle_redis_muc_store_script_extra_config }}'
  {%    endif %}
  {% endif %}
