---
# defaults file for m4e
cr_group: m4e.krestomat.io
cr_kind: M4e

# custom resource state: present, absent, suspended, inmaintenance
cr_state: present

meta_name_max_length: 26

# templates
moodle_config_template: moodle/config.php.j2
moodle_script_muc_store_template: moodle/muc-store.php.j2
moodle_script_status_template: moodle/status.php.j2
moodle_deploy_spec_template: deploy/moodle-spec.yaml.j2
moodle_new_instance_job_spec_template: job/moodle-new-instance-spec.yaml.j2
moodle_update_job_spec_template: job/moodle-update-spec.yaml.j2
moodle_cronjob_spec_template: cronjob/moodle-spec.yaml.j2

# common labels
meta_app_created_by: m4e-operator

# status
## moodle status version
moodle_status_version: "{{ (status_moodle_task.stdout | default({}) | from_json ).version | default([]) | first }}"
## whether moodle is uptodate
moodle_status_uptodate: "{{ cr_status_properties.uptodate | default('True') | bool }}"
## whether moodle is created
moodle_status_created: "{{ cr_status_properties.created | default('False') | bool }}"
moodle_status_script: "{{ moodle_scripts_path }}/status.php"
moodle_status_script_version: true
moodle_status_script_usage: true
moodle_status_script_checks: critical,error
