---
# nginx deploy
nginx_image: "{{ moodle_image }}"
nginx_container: "moodle-nginx"
nginx_connects_to: "{{ moodle_appname }}"

# ingress
nginx_ingress_host: "{{ moodle_host }}"
nginx_ingress_protocol: "{{ moodle_protocol }}"

# deploy
nginx_envvars:
  - name: MOODLE_CHECK_HOST
    value: '{{ nginx_host }}'
  - name: PHP_FPM_HOST
    value: '{{ moodle_service }}'
nginx_volumes:
  - name: moodledata
    mount_path: '{{ moodle_data }}'
    persistentVolumeClaim:
      claimName: '{{ moodle_pvc_moodledata }}'
