- name: nfs pvc resource definition
  vars:
    k8s_kind: PersistentVolumeClaim
    k8s_state: "{{ server_pvc_state | default(server_state) }}"
    template: "{{ pvc_template }}"
    metadata_name: "{{ server_pvc }}"
    pvc_spec: "{{ server_pvc_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save nfs pvc resource definition task
  set_fact:
    k8s_server_pvc: "{{ k8s_object_task }}"
