- name: set nfs server sts spec
  when: server_sts_spec is not defined
  vars:
    annotations: "{{ server_sts_spec_annotations | default(false) }}"
    extra_labels: "{{ server_sts_spec_extra_labels | default(false) }}"
    inventory_include: true
  set_fact:
    server_sts_spec: "{{ lookup('template', server_sts_spec_template) }}"

- name: nfs server sts resource definition
  vars:
    k8s_kind: StatefulSet
    k8s_state: "{{ server_sts_state | default(server_state) }}"
    k8s_wait: "{{ server_sts_wait | default(true) }}"
    k8s_wait_timeout: "{{ server_sts_wait_timeout | default(120) }}"
    template: "{{ sts_template }}"
    metadata_name: "{{ server_sts }}"
    annotations: "{{ server_sts_annotations | default(false) }}"
    sts_spec: "{{ server_sts_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save nfs server sts resource definition task
  set_fact:
    k8s_server_sts: "{{ k8s_object_task }}"

- name: wait for nfs server
  when:
    - k8s_server_sts is changed
    - "'absent' not in server_state | default(server_state)"
    - not ansible_check_mode
  retries: 12
  until:
    - (server_wait_task.resources | first).status.readyReplicas is defined
    - (server_wait_task.resources | first).status.readyReplicas == server_size
  k8s_info:
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ server_sts }}"
    namespace: "{{ meta_namespace }}"
  register: server_wait_task
