- name: moodle cronjob
  vars:
    moodle_component: "cronjob"
    metadata_name: "{{ moodle_cronjob }}"
    runtime: php-fpm
    annotations: "{{ moodle_cronjob_annotations | default(false) }}"
    extra_labels: "{{ moodle_cronjob_extra_labels | default(false) }}"
    connects_to: "{{ moodle_cronjob_connects_to }}"
  block:
    - name: set moodle cronjob spec
      when: moodle_cronjob_spec is not defined
      set_fact:
        moodle_cronjob_spec: "{{ lookup('template', moodle_cronjob_spec_template) }}"

    - name: moodle cronjob resource definition
      vars:
        k8s_kind: CronJob
        k8s_state: "{{ moodle_cronjob_state | default(moodle_state) }}"
        template: "{{ cronjob_template }}"
        cronjob_spec: "{{ moodle_cronjob_spec }}"
      include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle cronjob resource definition task
  set_fact:
    k8s_moodle_cronjob: "{{ k8s_object_task }}"
