- name: moodle new instance
  vars:
    moodle_component: "job-new-instance"
    metadata_name: "{{ moodle_new_instance_job }}"
    runtime: php-fpm
    annotations: "{{ moodle_new_instance_job_annotations | default(false) }}"
    extra_labels: "{{ moodle_new_instance_job_extra_labels | default(false) }}"
    connects_to: "{{ moodle_new_instance_job_connects_to }}"
  block:
    - name: set moodle new instance job spec
      when: moodle_new_instance_job_spec is not defined
      set_fact:
        moodle_new_instance_job_spec:
          "{{ lookup('template', moodle_new_instance_job_spec_template) }}"

    - name: moodle new instance job resource definition
      vars:
        k8s_kind: Job
        k8s_state: "{{ moodle_new_instance_job_state | default(moodle_state) }}"
        template: "{{ job_template }}"
        job_spec: "{{ moodle_new_instance_job_spec }}"
      include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle new instance job resource definition task
  set_fact:
    k8s_moodle_new_instance_job: "{{ k8s_object_task }}"
