- name: moodle nginx resource definition
  vars:
    k8s_kind: Nginx
    k8s_state: "{{ moodle_nginx_state | default(moodle_state) }}"
    template: "{{ nginx_template }}"
    metadata_name: "{{ moodle_nginx }}"
    annotations: "{{ moodle_nginx_annotations | default(false) }}"
    nginx_spec: "{{ moodle_nginx_spec }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle nginx resource definition task
  set_fact:
    k8s_moodle_nginx: "{{ k8s_object_task }}"

- name: wait for moodle nginx resource
  vars:
    wait_resource: "{{ k8s_moodle_nginx.result | default([]) }}"
  when:
    - not ansible_check_mode
    - k8s_moodle_nginx.result | default(false, true)
    - moodle_nginx_state | default(moodle_state) != 'absent'
    - moodle_nginx_wait | default(_moodle_k8s_wait) | default(true)
  include_tasks: "{{ common_path }}/wait/resource.yml"
