- name: moodle routine resource definition
  vars:
    k8s_kind: Routine
    k8s_state: "{{ 'absent' if cr_state == 'suspended' else moodle_routine_state | default(moodle_state) }}"
    template: "{{ routine_template }}"
    metadata_name: "{{ moodle_routine }}"
    annotations: "{{ inventory_annotation_extra_cr_cwd + (moodle_routine_annotations | default('')) }}"
    routine_spec: "{{ moodle_routine_spec }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle routine resource definition task
  set_fact:
    k8s_moodle_routine: "{{ k8s_object_task }}"
