- name: keep config.php in sync
  run_once: false
  no_log: true
  when:
    - moodle_config_autosync
    - hostvars['localhost'].k8s_moodle_secret_config is defined and
      hostvars['localhost'].k8s_moodle_secret_config is changed
  template:
    src: "{{ moodle_config_template }}"
    dest: "{{ moodle_app }}/config.php"
    mode: 0400
    validate: /usr/bin/php -l %s
