- name: wait job
  vars:
    wait_job_condition_failed: "{{ wait_job_conditions
      | selectattr('type', 'equalto', 'Failed') | first | default([]) }}"
    wait_job_condition_complete: "{{ wait_job_conditions
      | selectattr('type', 'equalto', 'Complete') | first | default([]) }}"
  block:
    - name: "check kind: Job, name: {{ wait_job_name }}"
      when: wait_job_condition_failed.status | default('False') | bool
      block:
        - name: remove failed job
          when: wait_job_remove_failed | default(false)
          k8s:
            state: absent
            definition:
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: "{{ wait_job_name }}"
                namespace: "{{ meta_namespace }}"

        - name: fail
          fail:
            msg: >-
              kind: Job, name: {{ wait_job_name }},
              msg: {{ wait_job_condition_failed.message | default('failed') }},
              reason: {{ wait_job_condition_failed.reason | default('') }}

    - name: "end play and wait new reconcile for kind: job, name: {{ wait_job_name }}"
      when: not wait_job_condition_complete.status | default('False') | bool
      block:
        - name: end play msg
          debug:
            msg: >-
              kind: Job, name: {{ wait_job_name }}, msg:
              waiting for a new reconciliation once its state changes because job has not been completed

        - name: end play
          meta: end_play
