- name: pgbouncer config map resource definition
  vars:
    k8s_kind: ConfigMap
    k8s_state: "{{ pgbouncer_cm_state | default(pgbouncer_state) }}"
    template: "{{ cm_template }}"
    metadata_name: "{{ pgbouncer_cm }}"
    cm_data: "{{ pgbouncer_cm_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save pgbouncer config map resource definition task
  set_fact:
    k8s_pgbouncer_cm: "{{ k8s_object_task }}"
