- name: pgbouncer deploy
  vars:
    metadata_name: "{{ pgbouncer_deploy }}"
    runtime: pgbouncer
    annotations: "{{ pgbouncer_deploy_annotations | default(false) }}"
    extra_labels: "{{ pgbouncer_deploy_extra_labels | default(false) }}"
    connects_to: "{{ pgbouncer_connects_to }}"
    inventory_include: true
  block:
    - name: set pgbouncer deploy spec
      when: pgbouncer_deploy_spec is not defined
      set_fact:
        pgbouncer_deploy_spec: "{{ lookup('template', pgbouncer_deploy_spec_template) }}"

    - name: pgbouncer deploy resource definition
      vars:
        k8s_kind: Deployment
        k8s_state: "{{ pgbouncer_deploy_state | default(pgbouncer_state) }}"
        k8s_wait: "{{ pgbouncer_deploy_wait | default(true) }}"
        k8s_wait_timeout: "{{ pgbouncer_deploy_wait_timeout | default(120) }}"
        template: "{{ deploy_template }}"
        deploy_spec: "{{ pgbouncer_deploy_spec }}"
      import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save pgbouncer deploy resource definition task
  set_fact:
    k8s_pgbouncer_deploy: "{{ k8s_object_task }}"
