- name: pgbouncer network policy resource definition
  vars:
    k8s_kind: NetworkPolicy
    k8s_state: "{{ pgbouncer_netpol_state | default(pgbouncer_state) }}"
    template: "{{ netpol_template }}"
    metadata_name: "{{ pgbouncer_netpol }}"
    netpol_spec: "{{ pgbouncer_netpol_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save pgbouncer netpol resource definition task
  set_fact:
    k8s_pgbouncer_netpol: "{{ k8s_object_task }}"
