- name: pgbouncer secret resource definition
  vars:
    k8s_kind: Secret
    k8s_state: "{{ pgbouncer_secret_state | default(pgbouncer_state) }}"
    template: "{{ secret_template }}"
    metadata_name: "{{ pgbouncer_secret }}"
    secret_data: "{{ pgbouncer_secret_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save pgbouncer secret resource definition task
  set_fact:
    k8s_pgbouncer_secret: "{{ k8s_object_task }}"
