- name: pgbouncer service resource definition
  vars:
    k8s_kind: Service
    k8s_state: "{{ pgbouncer_service_state | default(pgbouncer_state) }}"
    template: "{{ service_template }}"
    metadata_name: "{{ pgbouncer_service }}"
    service_spec: "{{ pgbouncer_service_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save pgbouncer service resource definition task
  set_fact:
    k8s_pgbouncer_service: "{{ k8s_object_task }}"
