- name: import tasks
  block:
    - name: handle initial status
      import_tasks: status/init.yml

    - name: handle postgres
      import_tasks: postgres.yml

    - name: handle moodle
      import_tasks: moodle.yml

    - name: handle nginx
      import_tasks: nginx.yml

    - name: end play without successful status
      when: not cr_status_properties.uptodate | default('True') | bool
      meta: end_play

    - name: include successful status
      import_tasks: condition/ready/successful.yml
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
