# moodle new instance
moodle_new_instance_job_needed:
  "{{ true if ((moodle_new_instance | bool) and not
  (cr_status_properties.instantiated | default('False') | bool)) else
  false }}"

# moodle update job
moodle_update_job_needed:
  "{{ true if not moodle_status_uptodate and moodle_status_version.pendingType | default('Other') in moodle_update_allow_pending_types else false }}"

# moodle data pvc
moodle_pvc_data_needed: "{{ false if moodle_nfs_meta_name else true }}"
