# general k8s state for resources: present or absent
state: present

# images
image_pull_secret: false

# inventory
inventory_include: false

# status
notify_status_jwt_secret_env_name: JWT_TOKEN_SECRET
