- name: import tasks
  block:
    - name: handle resources depending on postgres mode
      import_tasks: "{{ role_path }}/tasks/state/present/{{ postgres_mode }}.yml"

    - name: set suspended condition
      import_tasks: "{{ common_path }}/condition/suspended/suspended.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
