- name: get pvc info
  register: pvc_info_task
  when:
    - groups[pvc_info_container_group] | length > 0
    - groups[pvc_info_container_group][0] in groups[pods_ready_group]
  delegate_to: "{{ groups[pvc_info_container_group][0] }}"
  run_once: true
  krestomatio.k8s.pvc_info:
    path: "/{{ pvc_info_name }}"
    recommend_size: "{{ pvc_info_autoexpansion }}"
    increment_gib: "{{ pvc_info_increment_gib }}"
    cap_gib: "{{ pvc_info_cap_gib }}"

- name: set pvc status
  import_tasks: "{{ common_path }}/condition/expand/{{ 'required' if
    pvc_info_task.status.expansion_required | default(false) else 'not-required' }}.yml"
  vars:
    k8s_status_properties:
      pvc: "{{ { pvc_info_keyname : pvc_info_task.status } }}"
