# requires watchDependentResources=true
- name: trigger a CR reconciliation adding an annotation
  k8s:
    state: patched
    definition:
      apiVersion: "{{ reconcile_trigger_cr_group }}/{{ reconcile_trigger_cr_version }}"
      kind: "{{ reconcile_trigger_cr_kind }}"
      metadata:
        name: "{{ reconcile_trigger_cr_name }}"
        namespace: "{{ reconcile_trigger_cr_namespace }}"
        annotations: "{{ { reconcile_trigger_cr_group + '/reconcile-trigger':
         now(utc=True).isoformat(timespec='seconds') + 'Z' } }}"
