# requires watchDependentResources=true
- name: trigger parent CR reconciliation by adding an annotation
  vars:
    reconcile_trigger_value: "{{ cr_object.metadata.resourceVersion }}"
  k8s:
    state: patched
    definition:
      apiVersion: "{{ cr_api_version }}"
      kind: "{{ cr_kind }}"
      metadata:
        name: "{{ meta_name }}"
        namespace: "{{ meta_namespace }}"
        annotations: "{{ { cr_kind | lower + '.' + cr_group + '/reconcile-trigger':
         reconcile_trigger_value } }}"
