- name: moodle resource definitions
  vars:
    name: moodle
    k8s_state: "{{ moodle_state }}"
    component: "{{ moodle_component | default('moodle') }}"
    metadata_app: "{{ moodle_metadata_app | default(moodle_appname) }}"
  block:
    - import_tasks: resource/secret-admin.yml

    - import_tasks: resource/pvc-moodledata.yml

    - import_tasks: resource/secret-config.yml

    - include_tasks: resource/job-new-instance.yml
      when:
      - moodle_new_instance | bool
      - not (cr_status_properties.instantiated | default('False') | bool)

    - import_tasks: resource/deploy.yml

    - import_tasks: routine/status.yml

    - import_tasks: resource/cronjob.yml

    - include_tasks: resource/job-update.yml
      when:
        - status_version_update.type is defined
        - (status_version_update.type == 'minor' and moodle_update_minor) or
          (status_version_update.type == 'major' and moodle_update_major)

    - import_tasks: resource/service.yml

    - import_tasks: resource/routine.yml
