- name: moodle resource definitions
  vars:
    name: moodle
    k8s_state: "{{ moodle_state }}"
    component: "{{ moodle_component | default('moodle') }}"
    metadata_app: "{{ moodle_metadata_app | default(moodle_appname) }}"
  block:
    - name: deploy php-fpm and nginx ingress only without waiting while creating m4e
      when: not moodle_status_created and moodle_new_instance_job_needed
      vars:
        _moodle_k8s_wait: false
      block:
        - import_tasks: resource/nginx.yml
          vars:
            nginx_ingress_only: true

        - import_tasks: resource/php-fpm.yml

    - import_tasks: resource/secret-admin.yml

    - import_tasks: resource/pvc-moodledata.yml
      when: moodle_pvc_data_needed

    - import_tasks: resource/secret-config.yml

    - import_tasks: resource/cm-scripts.yml

    - import_tasks: resource/job-new-instance.yml
      when: moodle_new_instance_job_needed

    - import_tasks: resource/php-fpm.yml

    - meta: refresh_inventory

    - import_tasks: routine/status.yml

    - import_tasks: resource/cronjob.yml

    - include_tasks: resource/job-update.yml
      when: moodle_update_job_needed

    - import_tasks: resource/nginx.yml

    - import_tasks: resource/routine.yml
