- name: "assert namespace is '{{ servers_namespace }}'"
  assert:
    that:
      - meta_namespace == servers_namespace
    msg: "'Server' CR must be created in '{{ servers_namespace }}' namespace"

- name: import tasks
  block:
    - name: handle initial status
      import_tasks: status/init.yml

    - name: handle nfs
      import_tasks: nfs.yml

    - name: include successful status
      import_tasks: "{{ common_path }}/condition/ready/successful.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
