- name: nginx resource definitions
  vars:
    name: nginx
    k8s_state: "{{ nginx_state }}"
    component: nginx
    metadata_app: "{{ nginx_appname }}"
  block:
    - import_tasks: resource/netpol.yml
      when: not nginx_netpol_omit

    - name: handle all resources
      when: not nginx_ingress_only | bool and not nginx_route_only | bool
      block:
        - import_tasks: resource/cm.yml

        - import_tasks: resource/deploy.yml

        - import_tasks: resource/hpa.yml
          when: nginx_hpa_spec is defined and nginx_hpa_spec

        - import_tasks: resource/vpa.yml
          when: nginx_vpa_spec is defined and nginx_vpa_spec

        - import_tasks: resource/service.yml

    - import_tasks: "resource/{{ nginx_ingress_type }}.yml"
