- name: set state absent
  set_fact:
    state: absent
    k8s_wait: true

- name: import tasks
  block:
    - name: set terminating state
      vars:
        k8s_status_properties:
          state: Terminating
      import_tasks: "{{ common_path }}/k8s/status.yml"

    - name: handle server pvcs
      import_tasks: server-pvcs.yml

    - name: handle nfs
      import_tasks: nfs.yml
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
