- name: nfs resource definitions
  vars:
    name: nfs
    k8s_state: "{{ server_state }}"
    component: nfs
    metadata_app: "{{ server_appname }}"
  block:
    - import_tasks: resource/sc.yml

    - import_tasks: resource/server.yml

    - import_tasks: resource/pvc.yml
