- name: check if no pv's data/subdirs remain in server
  register: pvc_subdirs_task
  when:
    - server_container_group in groups
    - groups[server_container_group] | length > 0
    - groups[server_container_group][0] in groups[server_container_group]
  delegate_to: "{{ groups[server_container_group][0] }}"
  run_once: true
  retries: 6
  until: pvc_subdirs_task.matched is defined and pvc_subdirs_task.matched == 0
  failed_when: false
  find:
    path: "/{{ server_pvc }}"
    file_type: directory
    depth: 1
    excludes: "{{ pvc_subdir_check_excludes | default('lost+found') }}"

- name: fail if any pv's data still present
  fail:
    msg: Data from PV's remain in this NFS server
  when: pvc_subdirs_task.matched is defined and pvc_subdirs_task.matched > 0
