- name: set successful status
  import_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_status_cr_notify_force: true
    routine_k8s_status_properties:
      ready: "True"
      state: Ready
      storageClass: "{{ server_generated_nfs_sc
        if server_generated_nfs_sc_needed else '' }}"
      service: "{{ server_service + '.' + meta_namespace }}"
    routine_k8s_status_conditions:
      - type: "Ready"
        status: "True"
        reason: "Successful"
        message: "All tasks completed successfully"
