- name: set moodle deploy spec
  when: moodle_deploy_spec is not defined
  vars:
    annotations: "{{ moodle_deploy_spec_annotations | default(false) }}"
    extra_labels: "{{ moodle_deploy_spec_extra_labels | default(false) }}"
    inventory_include: true
  set_fact:
    moodle_deploy_spec: "{{ lookup('template', moodle_deploy_spec_template) }}"

- name: moodle deploy resource definition
  vars:
    k8s_kind: Deployment
    k8s_state: "{{ moodle_deploy_state | default(moodle_state) }}"
    k8s_wait: "{{ moodle_deploy_wait | default(true) }}"
    k8s_wait_timeout: "{{ moodle_deploy_wait_timeout | default(120) }}"
    template: "{{ deploy_template }}"
    metadata_name: "{{ moodle_deploy }}"
    annotations: "{{ moodle_deploy_annotations | default(false) }}"
    connects_to: "{{ moodle_connects_to }}"
    runtime: php
    deploy_spec: "{{ moodle_deploy_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle deploy resource definition task output
  set_fact:
    k8s_moodle_deploy: "{{ k8s_object_task }}"
