- name: moodle nginx resource definition
  vars:
    nginx_annotation_inventory_extra_cr_cwd: |
      krestomat.io/inventory-extra-cr-cwd: '{{ cr_cwd }}'
    k8s_kind: Nginx
    k8s_state: "{{ moodle_nginx_state | default(moodle_state) }}"
    k8s_wait:
      "{{ false if moodle_nginx_state | default(moodle_state) == 'absent' or
      moodle_ingress_only | bool else true }}"
    k8s_wait_condition:
      type: "Ready"
      status: "True"
    template: "{{ nginx_template }}"
    metadata_name: "{{ moodle_nginx }}"
    annotations: "{{ nginx_annotation_inventory_extra_cr_cwd + (moodle_nginx_annotations | default('')) }}"
    nginx_spec: "{{ moodle_nginx_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle nginx resource definition task
  set_fact:
    k8s_moodle_nginx: "{{ k8s_object_task }}"
