- name: moodle php-fpm resource definition
  vars:
    k8s_kind: Phpfpm
    k8s_state: "{{ moodle_php_fpm_state | default(moodle_state) }}"
    template: "{{ php_fpm_template }}"
    metadata_name: "{{ moodle_php_fpm }}"
    annotations: "{{ moodle_php_fpm_annotations | default(false) }}"
    php_fpm_spec: "{{ moodle_php_fpm_spec }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle php-fpm resource definition task
  set_fact:
    k8s_moodle_php_fpm: "{{ k8s_object_task }}"

- name: wait for moodle php-fpm resource
  when:
    - not ansible_check_mode
    - moodle_php_fpm_state | default(moodle_state) != 'absent'
    - moodle_php_fpm_wait | default(_moodle_k8s_wait) | default(true)
    - k8s_moodle_php_fpm is defined and k8s_moodle_php_fpm is changed
  retries: 12
  delay: 5
  until:
    - k8s_moodle_php_fpm_previous_resource_version != k8s_moodle_php_fpm_resource_version
    - k8s_moodle_php_fpm_condition_ready and k8s_moodle_php_fpm_condition_ready.status is match('True')
    - k8s_moodle_php_fpm_condition_successful and k8s_moodle_php_fpm_condition_successful.status is match('True')
  vars:
    k8s_moodle_php_fpm_previous_resource_version:
      "{{ k8s_moodle_php_fpm.result.metadata.resourceVersion | default('1') }}"
    k8s_moodle_php_fpm_resource_version: "{{ (k8s_moodle_php_fpm_wait.resources |
      default([]) | first).metadata.resourceVersion | default('2') }}"
    k8s_moodle_php_fpm_object: "{{ k8s_moodle_php_fpm_wait.resources | default([]) | first | default([]) }}"
    k8s_moodle_php_fpm_conditions: "{{ k8s_moodle_php_fpm_object.status.conditions | default([]) }}"
    k8s_moodle_php_fpm_condition_ready: "{{ k8s_moodle_php_fpm_conditions |
      selectattr('type', 'equalto', 'Ready') | first | default ([]) }}"
    k8s_moodle_php_fpm_condition_successful: "{{ k8s_moodle_php_fpm_conditions |
      selectattr('type', 'equalto', 'Successful') | first | default ([]) }}"
  k8s_info:
    api_version: "{{ php_fpm_cr_api_version | default(cr_api_version) }}"
    kind: Phpfpm
    name: "{{ moodle_php_fpm }}"
    namespace: "{{ meta_namespace }}"
  register: k8s_moodle_php_fpm_wait
