- name: set state absent
  set_fact:
    state: absent
    k8s_wait: true

- name: import tasks
  block:
    - name: start terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/start.yml"
      delegate_to: localhost

    - name: handle routine removal
      import_tasks: "{{ role_path }}/tasks/routine.yml"

    - name: end terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/end.yml"
      delegate_to: localhost
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
      delegate_to: localhost
