- name: import tasks
  block:
    - name: make assertions
      import_tasks: "{{ role_path }}/tasks/assertions.yml"

    - name: handle postgres
      import_tasks: "{{ role_path }}/tasks/postgres.yml"

    - name: handle pgbouncer
      import_tasks: "{{ role_path }}/tasks/pgbouncer.yml"

    - name: handle postgres read replicas
      import_tasks: "{{ role_path }}/tasks/readreplicas.yml"

    - name: handle pgbouncer readonly
      import_tasks: "{{ role_path }}/tasks/pgbouncer-readonly.yml"

    - name: include successful status
      import_tasks: "{{ role_path }}/tasks/condition/ready/successful.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
