- import_tasks: routine/status.yml

- name: set uptodate fact
  set_fact:
    routine_moodle_status_uptodate: "{{ cr_status_properties.uptodate | default('True') | bool }}"

- when: k8s_status_task is defined and k8s_status_task is changed
  import_tasks: "{{ common_path }}/reconcile-trigger.yml"
