# defaults file for m4e
cr_group: nfs.krestomat.io
cr_kind: Routine

# custom resource state: present, absent
cr_state: present

meta_name_max_length: 56

# common labels
meta_app_created_by: nfs-operator
