- name: get mount info
  register: mount_info_task
  mount_info:
    path: "/{{ server_pvc }}"

- name: set mount info in nfs status
  import_tasks: "{{ common_path }}/k8s/status.yml"
  when: mount_info_task.mount_info is defined and mount_info_task.mount_info
  delegate_to: localhost
  vars:
    k8s_status_properties:
      usage:
        - description: Storage available
          name: size_available
          unit: GB
          value: "{{ mount_info_task.mount_info.size_available | krestomatio.k8s.b_to_gb }}"
        - description: Total storage
          name: size_total
          unit: GB
          value: "{{ mount_info_task.mount_info.size_total | krestomatio.k8s.b_to_gb }}"
