- name: routine to keep config.php in sync
  run_once: false
  no_log: true
  when:
    - routine_moodle_config_autosync
    - routine_sync_config_php is defined and routine_sync_config_php
  vars:
    routine_sync_config_php: "{{ lookup('k8s', kind='Secret', namespace=routine_reconcile_trigger_cr_namespace,
      resource_name=routine_moodle_secret_config ).data['config.php'] |
      default('') | b64decode }}"
  copy:
    content: "{{ routine_sync_config_php }}"
    dest: "{{ routine_moodle_app }}/config.php"
    mode: 0400
    validate: /usr/bin/php -l %s
