- name: set error status
  import_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_k8s_status_properties:
      ready: "False"
      state: Terminating
    routine_k8s_status_conditions:
      - type: "Ready"
        status: "False"
        reason: "Terminating"
        message: "Finalizer started"
