- name: graphql-engine route resource definition
  vars:
    k8s_kind: Route
    k8s_state: "{{ graphql_engine_route_state | default(graphql_engine_state) }}"
    template: "{{ route_template }}"
    metadata_name: "{{ graphql_engine_route }}"
    annotations: "{{ graphql_engine_route_annotations | default(false) }}"
    route_spec: "{{ graphql_engine_route_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save graphql-engine route resource definition task
  set_fact:
    k8s_graphql_engine_route: "{{ k8s_object_task }}"
