- name: graphql-engine handler ecret resource definition
  vars:
    k8s_kind: Secret
    k8s_state: "{{ graphql_engine_secret_handler_state | default(graphql_engine_state) }}"
    template: "{{ secret_template }}"
    metadata_name: "{{ graphql_engine_secret_handler }}"
    secret_data: "{{ graphql_engine_secret_handler_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save graphql-engine handler secret resource definition task
  set_fact:
    k8s_graphql_engine_secret_handler: "{{ k8s_object_task }}"
