- name: graphql-engine service resource definition
  vars:
    k8s_kind: Service
    k8s_state: "{{ graphql_engine_pvc_state | default(graphql_engine_state) }}"
    template: "{{ service_template }}"
    metadata_name: "{{ graphql_engine_service }}"
    service_spec: "{{ graphql_engine_service_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save graphql-engine service resource definition task
  set_fact:
    k8s_graphql_engine_service: "{{ k8s_object_task }}"
