- name: set k8s resources state to absent
  set_fact:
    state: absent

- name: set routine status cr notify termination
  when: routine_status_cr_notify_termination is defined and routine_status_cr_notify_termination
  set_fact:
    routine_status_cr_notify: "{{ routine_status_cr_notify_termination }}"

- name: import tasks
  block:
    - name: start terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/start.yml"

    - name: handle moodle removal
      import_tasks: "{{ role_path }}/tasks/state/absent/moodle.yml"

    - name: end terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/end.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
