- name: moodle resource definitions
  vars:
    name: moodle
    k8s_state: "{{ moodle_state }}"
    component: "{{ moodle_component | default('moodle') }}"
    metadata_app: "{{ moodle_metadata_app | default(moodle_appname) }}"
  block:
    # remove crd
    - import_tasks: "{{ role_path }}/tasks/resource/routine.yml"

    - import_tasks: "{{ role_path }}/tasks/resource/nginx.yml"

    - import_tasks: "{{ role_path }}/tasks/resource/php-fpm.yml"
