- name: moodle service resource definition
  vars:
    k8s_kind: Service
    k8s_state: "{{ moodle_service_state | default(moodle_state) }}"
    template: "{{ service_template }}"
    metadata_name: "{{ moodle_service }}"
    service_spec: "{{ moodle_service_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle service resource definition task
  set_fact:
    k8s_moodle_service: "{{ k8s_object_task }}"
