- name: postgres env vars config map resource definition
  vars:
    k8s_kind: ConfigMap
    k8s_state: "{{ postgres_cm_vars_state | default(postgres_state) }}"
    template: "{{ cm_template }}"
    metadata_name: "{{ postgres_cm_vars }}"
    cm_data: "{{ postgres_cm_vars_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save postgres env vars config map resource definition task
  set_fact:
    k8s_postgres_cm_vars: "{{ k8s_object_task }}"
