- name: postgres network policy resource definition
  vars:
    k8s_kind: NetworkPolicy
    k8s_state: "{{ postgres_netpol_state | default(postgres_state) }}"
    template: "{{ netpol_template }}"
    metadata_name: "{{ postgres_netpol }}"
    netpol_spec: "{{ postgres_netpol_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save postgres netpol resource definition task
  set_fact:
    k8s_postgres_netpol: "{{ k8s_object_task }}"
