- name: import tasks
  block:
    - name: handle (nfs) ganesha server removal
      import_tasks: "{{ role_path }}/tasks/ganesha.yml"

    - name: set suspended condition
      import_tasks: "{{ common_path }}/condition/suspended/suspended.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
