- name: php-fpm config map resource definition
  vars:
    k8s_kind: ConfigMap
    k8s_state: "{{ php_fpm_cm_state | default(php_fpm_state) }}"
    template: "{{ cm_template }}"
    metadata_name: "{{ php_fpm_cm }}"
    cm_data: "{{ php_fpm_cm_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save php-fpm config map resource definition task
  set_fact:
    k8s_php_fpm_cm: "{{ k8s_object_task }}"
