- name: php-fpm deploy
  vars:
    metadata_name: "{{ php_fpm_deploy }}"
    runtime: php-fpm
    annotations: "{{ php_fpm_deploy_annotations | default(false) }}"
    extra_labels: "{{ php_fpm_deploy_extra_labels | default(false) }}"
    connects_to: "{{ php_fpm_connects_to }}"
    inventory_include: true
  block:
    - name: set php-fpm deploy spec
      when: php_fpm_deploy_spec is not defined
      set_fact:
        php_fpm_deploy_spec: "{{ lookup('template', php_fpm_deploy_spec_template) }}"

    - name: php-fpm deploy resource definition
      vars:
        k8s_kind: Deployment
        k8s_state: "{{ php_fpm_deploy_state | default(php_fpm_state) }}"
        k8s_wait: "{{ php_fpm_deploy_wait | default(true) }}"
        k8s_wait_timeout: "{{ php_fpm_deploy_wait_timeout | default(120) }}"
        template: "{{ deploy_template }}"
        deploy_spec: "{{ php_fpm_deploy_spec }}"
      import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save php-fpm deploy resource definition task output
  set_fact:
    k8s_php_fpm_deploy: "{{ k8s_object_task }}"
