- name: php-fpm network policy resource definition
  vars:
    k8s_kind: NetworkPolicy
    k8s_state: "{{ php_fpm_netpol_state | default(php_fpm_state) }}"
    template: "{{ netpol_template }}"
    metadata_name: "{{ php_fpm_netpol }}"
    netpol_spec: "{{ php_fpm_netpol_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save php-fpm netpol resource definition task
  set_fact:
    k8s_php_fpm_netpol: "{{ k8s_object_task }}"
