- name: php-fpm vpa resource definition
  vars:
    k8s_kind: VerticalPodAutoscaler
    k8s_state: "{{ php_fpm_vpa_state | default(php_fpm_state) }}"
    template: "{{ vpa_template }}"
    metadata_name: "{{ php_fpm_vpa }}"
    annotations: "{{ php_fpm_vpa_annotations | default(false) }}"
    vpa_ref_api_version: apps/v1
    vpa_ref_kind: Deployment
    vpa_ref_name: "{{ php_fpm_deploy }}"
    vpa_spec: "{{ php_fpm_vpa_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save php-fpm vpa resource definition task
  set_fact:
    k8s_php_fpm_vpa: "{{ k8s_object_task }}"
