- name: set successful status
  include_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_status_cr_notify_force: true
    this_routine_k8s_status_properties:
      ready: "True"
      state: "Ready"
    routine_k8s_status_properties:
      "{{ this_routine_k8s_status_properties | combine({'observedGeneration': cr_status_generation | int}) }}"
    routine_k8s_status_conditions:
      - type: "Suspended"
        status: "False"
        reason: "NotSuspended"
        message: "Resource is not suspended"
      - type: "Ready"
        status: "True"
        reason: "Successful"
        message: "All tasks completed successfully"

# to trigger reconciliation in parent CR, watchDependentResources=true is required
- name: add observed generation annotation
  vars:
    add_annotations: "{{ { cr_group + '/observedGeneration':  cr_status_generation, cr_group + '/ready':  'True'} }}"
  include_tasks: "{{ common_path }}/add-annotations.yml"
