- name: reset admin hash pass
  when:
    - routine_moodle_new_adminpass_hash is defined
    - routine_moodle_container_group in groups
    - groups[routine_moodle_container_group] | length > 0
    - groups[routine_moodle_container_group][0] in groups[routine_pods_ready_group]
  delegate_to: "{{ groups[routine_moodle_container_group][0] }}"
  run_once: true
  register: routine_reset_admin_pass_task
  command: "php ${MOODLE_CLI_TOOLS}/reset-user-pass.php --userid=2 --hash='{{ moodle_new_adminpass_hash }}'"
