# THIS FILES IS SHARED BETWEEN M4E.M4E AND ROUTINE.M4E CRD

- name: get moodle status
  when:
    - routine_moodle_container_group in groups
    - groups[routine_moodle_container_group] | length > 0
    - groups[routine_moodle_container_group][0] in groups[routine_pods_ready_group]
  delegate_to: "{{ groups[routine_moodle_container_group][0] }}"
  changed_when: false
  run_once: true
  register: routine_status_moodle_task
  command: "{{ routine_moodle_status_script }}"

- name: set moodle properties status and uptodate condition
  when: routine_k8s_status_properties | default(false, true)
  vars:
    routine_k8s_status_properties: "{{ routine_status_moodle_task.stdout | default('{}',true) | from_json }}"
    routine_k8s_status_replace_lists: true
    routine_status_moodle_version_condition:
      "{{ 'uptodate' if (routine_k8s_status_properties.uptodate | default('True') | bool) else
        ('downgraded' if (routine_k8s_status_properties.version.downgrade_error |
        default('False') | bool) else 'pending') }}"
  include_tasks: "condition/uptodate//{{ routine_status_moodle_version_condition }}.yml"
