- name: get moodle status
  when:
    - moodle_container_group in groups
    - groups[moodle_container_group] | length > 0
    - groups[moodle_container_group][0] in groups[pods_ready_group]
  delegate_to: "{{ groups[moodle_container_group][0] }}"
  changed_when: false
  run_once: true
  register: status_moodle_task
  command: "{{ moodle_status_script }} -l {{ '-v' if
    moodle_status_script_version else '' }} {{ '-u' if
    moodle_status_script_usage else '' }}{% if moodle_status_script_checks is defined and
    moodle_status_script_checks %} -c='{{ moodle_status_script_checks }}'{% endif %}"

- name: set moodle uptodate condition
  vars:
    k8s_status_replace_lists: true
  include_tasks: "{{ moodle_status_uptodate_condition }}"
