- name: set (nfs) server volume claim template
  vars:
    metadata_name: "{{ server_pvc_data }}"
    annotations: "{{ server_pvc_data_annotations | default(false) }}"
    extra_labels: "{{ server_pvc_data_extra_labels | default(false) }}"
    namespaced: false
    pvc_spec: "{{ server_pvc_data_spec }}"
  set_fact:
    server_volume_claim_template: "{{ [lookup('template', vct_template) | from_yaml] }}"

- name: set (nfs) server statefulset spec
  when: server_sts_spec is not defined
  vars:
    annotations: "{{ server_sts_spec_annotations | default(false) }}"
    extra_labels: "{{ server_sts_spec_extra_labels | default(false) }}"
    inventory_include: true
  set_fact:
    server_sts_spec: "{{ lookup('template', server_sts_spec_template) }}"

# workaround for sts volume expansion until https://github.com/kubernetes/enhancements/pull/2842
- name: save (nfs) server statefulset pvc current and new sizes
  set_fact:
    server_sts_pvc_expansion_data_size: "{{ server_pvc_data_size }}"
    server_sts_pvc_expansion_data_current_size: "{{ server_pvc_data_current_size }}"

- name: allow (nfs) server statefulset pvc expansion
  when:
    - server_sts_pvc_expansion_data_current_size is defined and server_sts_pvc_expansion_data_current_size
    - server_sts_pvc_expansion_data_current_size != server_sts_pvc_expansion_data_size
    - server_sts_pvc_expansion_list | length > 0
    - "server_sts_state | default(server_state) != 'absent'"
  vars:
    server_sts_pvc_expansion_label_selector: "app={{ metadata_app }}"
    server_sts_pvc_expansion_list: "{{ query('k8s', api_version='v1', kind='PersistentVolumeClaim',
      namespace=meta_namespace,label_selector=server_sts_pvc_expansion_label_selector) | default([]) }}"
  block:
    - name: delete (nfs) server statefulset without removing pods and data
      k8s:
        state: absent
        delete_options:
          propagationPolicy: Orphan
        definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: "{{ server_sts }}"
            namespace: "{{ meta_namespace }}"
      register: k8s_server_sts_delete_orphan_task

    - name: patch (nfs) server statefulset pvc(s)
      loop: "{{ server_sts_pvc_expansion_list }}"
      k8s:
        state: patched
        definition:
          apiVersion: "{{ item.apiVersion }}"
          kind: "{{ item.kind }}"
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ item.metadata.namespace }}"
          spec:
            resources:
              requests:
                storage: "{{ server_sts_pvc_expansion_data_size }}"
###### end of workaround ######

- name: (nfs) server statefulset resource definition
  vars:
    k8s_kind: StatefulSet
    k8s_state: "{{ server_sts_state | default(server_state) }}"
    k8s_wait: "{{ server_sts_wait | default(true) }}"
    k8s_wait_timeout: "{{ server_sts_wait_timeout | default(200) }}"
    template: "{{ sts_template }}"
    metadata_name: "{{ server_sts }}"
    annotations: "{{ server_sts_annotations | default(false) }}"
    runtime: ganesha
    sts_spec: "{{ server_sts_spec }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save (nfs) server statefulset resource definition task output
  set_fact:
    k8s_server_sts: "{{ k8s_object_task }}"
