---
# defaults file for m4e
cr_version: v1alpha1
# cr_group: sample.krestomat.io
cr_api_version: "{{ cr_group }}/{{ cr_version }}"
# cr_kind: Sample

meta_name: "{{ ansible_operator_meta.name }}"
meta_namespace: "{{ ansible_operator_meta.namespace }}"
pods_group: "{{ cr_kind }}__{{ meta_namespace.replace('-', '_') }}__{{ meta_name.replace('-', '_') }}__pods"
pods_ready_group: "{{ pods_group }}_ready"

# general k8s state for resources: present or absent
state: present

# templates
deploy_template: deploy.yaml.j2
job_template: job.yaml.j2
cronjob_template: cronjob.yaml.j2
config_template: config.yaml.j2
pvc_template: pvc.yaml.j2
secret_template: secret.yaml.j2
service_template: service.yaml.j2
route_template: route.yaml.j2
ingress_template: ingress.yaml.j2

# inventory
inventory_include: false
inventory_uuid: '{{ (cr_group + cr_version + cr_kind + meta_namespace + meta_name) | to_uuid }}'
annotation_inventory_hostvars:
  ansible_remote_tmp: /var/tmp/.ansible
  ansible_python_interpreter: /usr/libexec/platform-python
