---
# defaults file for m4e
cr_group: m4e.krestomat.io
cr_kind: M4e

# custom resource state: present, absent, suspended, inmaintenance
cr_state: present

meta_name_max_length: 26

# expose
expose_type: "{{ 'route' if (k8s_distribution | default('k8s')) == 'okd' else 'ingress' }}"
expose_tls: false
expose_tls_secret_name: false

# url
host: "m4e"
domain: "krestomat.io"
fqdn: "{{ host }}.{{ domain }}"

# templates
moodle_config_template: moodle/config.php.j2
postgres_deploy_spec_template: deploy/postgres-spec.yaml.j2
moodle_deploy_spec_template: deploy/moodle-spec.yaml.j2
nginx_deploy_spec_template: deploy/nginx-spec.yaml.j2
moodle_new_instance_job_spec_template: job/moodle-new-instance-spec.yaml.j2
moodle_update_job_spec_template: job/moodle-update-spec.yaml.j2
moodle_cronjob_spec_template: cronjob/moodle-spec.yaml.j2

# images
image_pull_secret: false

# common labels
meta_app_part_of: moodle
meta_app_created_by: m4e-operator
