- name: keydb resource definitions
  vars:
    name: keydb
    k8s_state: "{{ keydb_state }}"
    component: keydb
    metadata_app: "{{ keydb_appname }}"
  block:
    - import_tasks: resource/secret.yml

    - import_tasks: resource/cm.yml

    - import_tasks: resource/svc-headless.yml

    - import_tasks: resource/svc.yml

    - import_tasks: resource/sts.yml

    - import_tasks: resource/vpa.yml
      when: keydb_vpa_spec is defined and keydb_vpa_spec

    - import_tasks: "{{ common_path }}/cleanup-resources.yml"
      vars:
        cleanup_label_selector: "app={{ metadata_app }}"
        cleanup_kind_list:
          - PersistentVolumeClaim
